name: tests
on:
  push:
  pull_request:
    branches: [master]
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  VLADO_COIN_CONTRACT_ADDRESS: ${{ secrets.VLADO_COIN_CONTRACT_ADDRESS }}
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - name: use cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Check
        run: echo "The VLADO_COIN_CONTRACT_ADDRESS is:${{env.VLADO_COIN_CONTRACT_ADDRESS}}"
      - name: Compile
        run: npx hardhat compile
      - name: Run unit tests
        run: npm run test
