name: tests
on:
  pull_request:
    branches: [master]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - name: Use cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: .env tests
        run: echo TEST=${{ secrets.TEST }}
      # - name: Create .env file
      #   run: |
      #     touch .env
      #     echo PROD_ALCHEMY_KEY=${{ secrets.PROD_ALCHEMY_KEY }} >> .env
      #     echo DEV_ALCHEMY_KEY=${{ secrets.DEV_ALCHEMY_KEY }} >> .env
      #     echo ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }} >> .env
      #     echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env
      #     echo DEPLOYED_CONTRACT_ADDRESS=${{ secrets.DEPLOYED_CONTRACT_ADDRESS }} >> .env
      #     echo VLADO_COIN_CONTRACT_ADDRESS=${{ secrets.VLADO_COIN_CONTRACT_ADDRESS }} >> .env
      # - name: Install dependencies
      #   run: npm install
      # - name: Compile
      #   run: npx hardhat compile
      # - name: Run unit tests
      #   run: npm run test
