name: tests
on:
  pull_request:
    branches: [master]
jobs:
  unit-tests:
    environment: Web3Wall
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - name: use cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        env:
          PROD_ALCHEMY_KEY: ${{ secrets.PROD_ALCHEMY_KEY }}
          DEV_ALCHEMY_KEY: ${{ secrets.DEV_ALCHEMY_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DEPLOYED_CONTRACT_ADDRESS: ${{ secrets.DEPLOYED_CONTRACT_ADDRESS }}
          VLADO_COIN_CONTRACT_ADDRESS: ${{ secrets.VLADO_COIN_CONTRACT_ADDRESS }}
        run: npm install
      - name: Compile
        run: npx hardhat compile
      - name: Run unit tests
        run: npm run test
